# Generated by Django 4.2.7 on 2023-12-03 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_back', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 21, 11, 37, 851120)),
        ),
    ]
