# Generated by Django 4.2.7 on 2023-12-03 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_back', '0004_advisor_professor_student_delete_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='office_hours',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 21, 39, 4, 920823)),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 21, 39, 4, 920845)),
        ),
    ]
